language: python
python:
  - "2.7"
  - "3.6"
env:
  global:
    - MAIN_PYTHON_VERSION="2.7"
    - MAIN_TF_VERSION="1.6.*"
  matrix:
    - TF_VERSION="1.4.*"
    - TF_VERSION="1.5.*"
    - TF_VERSION="1.6.*"
    - TF_VERSION="1.7.*"
matrix:
  exclude:
    - python: "3.6"
      env: TF_VERSION="1.4.*"
    - python: "3.6"
      env: TF_VERSION="1.5.*"
before_install:
  - pip install tensorflow==$TF_VERSION
  - pip install -e .[tests]
  - |
        if [[ "$TRAVIS_PYTHON_VERSION" == "$MAIN_PYTHON_VERSION" && "$TF_VERSION" == "$MAIN_TF_VERSION" ]]; then
            pip install pylint==1.8.2
            pip install sphinx==1.6.7
            pip install sphinxcontrib-versioning
            pip install sphinx_rtd_theme
            pip install recommonmark
            pip install wheel
            pip install twine
        fi
script:
  - nose2
  - if [[ "$TRAVIS_PYTHON_VERSION" == "$MAIN_PYTHON_VERSION" && "$TF_VERSION" == "$MAIN_TF_VERSION" ]]; then pylint opennmt/; fi
after_success:
  - |
        if [[ "$TRAVIS_PYTHON_VERSION" == "$MAIN_PYTHON_VERSION" && "$TF_VERSION" == "$MAIN_TF_VERSION" && -n $TRAVIS_TAG ]]; then
            eval "$(ssh-agent -s)"; touch docs/key; chmod 0600 docs/key
            openssl aes-256-cbc -K $encrypted_6389583f9019_key -iv $encrypted_6389583f9019_iv -in docs/key.enc -out docs/key -d && ssh-add docs/key
            git config --global user.email "builds@travis-ci.com"
            git config --global user.name "Travis CI"
            git remote set-url --push origin "git@github.com:$TRAVIS_REPO_SLUG"
            sphinx-versioning push -e .nojekyll docs gh-pages .
            python setup.py sdist bdist_wheel --universal
            twine upload dist/*
        fi
